"use strict";
function smartMockReply(text){
  const t=(text||'').toLowerCase();
  const slug=(text||'').replace(/^\/(create|scan|fix|explain|make|build|do)\s*/i,'').trim()||'game system';
  const name=slug.split(/\s+/).slice(0,2).map(w=>((w[0]||'').toUpperCase()+w.slice(1).toLowerCase())).join('').replace(/[^A-Za-z]/g,'')||'Script';

  if(/coin|currency|gold|money|cash|dollar|econ/.test(t))return coinTpl(name);
  if(/sword|weapon|tool|gun|knife|combat/.test(t))return swordTpl(name);
  if(/pet|companion|follow|minion/.test(t))return petTpl(name);
  if(/round|match|battle|arena|br |battle royale|minigame/.test(t))return roundTpl(name);
  if(/admin|command|ban|kick|mod/.test(t))return adminTpl(name);
  if(/tycoon|dropper|factory|printer/.test(t))return tycoonTpl(name);
  if(/leaderboard|leaderstats|kill|score|stat/.test(t))return lbTpl(name);
  if(/shop|store|buy|purchase|item/.test(t))return shopTpl(name);
  if(/obby|jump|parkour|platform|checkpoint/.test(t))return obbyTpl(name);
  if(/datastore|save|persist|save data/.test(t))return dsTpl(name);
  if(/fix|error|bug|broken|doesn.?t work|not work|help/.test(t))return fixTpl(slug);
  if(/explain|how|what is|why|learn/.test(t))return explainTpl(slug);
  return genericTpl(name,slug);
}
const KEYNOTE = "\n\n---\n💡 **Tip:** Add a **free DeepSeek key** in ⚙️ Settings (https://platform.deepseek.com — they give $5 free credits, no credit card) for unlimited full AI that can read your whole project and write any system.\n\nEven without a key, the templates above are **real runnable Roblox Luau** — click 📤 Send to Studio under each block to insert into your game.";

function loc(line){return line;}

function coinTpl(n){return `## 🪙 Coin System\n\nPickup-coin system: players touch coins, earn gold, leaderstats auto-updates, coins spin+bob. Drop parts in workspace tagged **Coin**.\n\n### Build plan\n- Server: leaderstats + touch detection (debounced)\n- Client: spin & bob visuals via TweenService\n\n\`\`\`lua\n-- @location ServerScriptService.CoinService\nlocal Players=game:GetService(\"Players\")\nlocal CollectionService=game:GetService(\"CollectionService\")\nPlayers.PlayerAdded:Connect(function(p)\n  local ls=Instance.new(\"Folder\");ls.Name=\"leaderstats\"\n  local g=Instance.new(\"IntValue\");g.Name=\"Gold\";g.Value=0;g.Parent=ls\n  ls.Parent=p\nend)\nlocal function setup(coin)\n  local part=coin:IsA(\"BasePart\")and coin or coin:FindFirstChildWhichIsA(\"BasePart\")\n  if not part or part:GetAttribute(\"CoinBound\")then return end\n  part:SetAttribute(\"CoinBound\",true)\n  local db=false\n  part.Touched:Connect(function(hit)\n    if db then return end\n    local pl=Players:GetPlayerFromCharacter(hit.Parent)\n    if not pl then return end\n    db=true\n    local ls=pl:FindFirstChild(\"leaderstats\")\n    if ls and ls.Gold then ls.Gold.Value+=1 end\n    coin:Destroy()\n  end)\nend\nfor _,c in CollectionService:GetTagged(\"Coin\")do task.spawn(setup,c)end\nCollectionService:GetInstanceAddedSignal(\"Coin\"):Connect(setup)\n\`\`\`\n\n\`\`\`lua\n-- @location StarterPlayerScripts.CoinVisuals\nlocal CS=game:GetService(\"CollectionService\")\nlocal TS=game:GetService(\"TweenService\")\nlocal function spin(c)\n  local p=c:IsA(\"BasePart\")and c or c:FindFirstChildWhichIsA(\"BasePart\")\n  if not p then return end\n  p.Anchored=true;p.CanCollide=false;p.Material=Enum.Material.Neon;p.Color=Color3.new(1,0.85,0)\n  TS:Create(p,TweenInfo.new(2,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,-1,true),{Position=p.Position+Vector3.new(0,0.6,0)}):Play()\n  TS:Create(p,TweenInfo.new(4,Enum.EasingStyle.Linear,Enum.EasingDirection.InOut,-1),{CFrame=p.CFrame*CFrame.Angles(0,math.rad(360),0)}):Play()\nend\nfor _,c in CS:GetTagged(\"Coin\")do spin(c)end\nCS:GetInstanceAddedSignal(\"Coin\"):Connect(spin)\n\`\`\`\n\n**Setup:** In Studio, open View → Tag Editor, create a tag **Coin**, and apply it to any Part in Workspace.` + KEYNOTE;}

function swordTpl(n){return `## ⚔️ Sword Tool\n\nClick-to-swing sword with damage, cooldown, knockback. Works with default Roblox characters.\n\n\`\`\`lua\n-- @location StarterPack.Sword.SwordScript\nlocal Tool=script.Parent;local Handle=Tool:WaitForChild(\"Handle\")\nlocal DAMAGE=30;local CD=0.5;local active=false\nTool.Activated:Connect(function()\n  if not active then return end\n  active=false\n  local char=Tool.Parent;local hum=char:FindFirstChildOfClass(\"Humanoid\")\n  if not hum then return end\n  local hits={}\n  for _,p in ipairs(Handle:GetTouchingParts())do\n    local h=p.Parent:FindFirstChildOfClass(\"Humanoid\")\n    if h and p.Parent~=char and not hits[h]then\n      hits[h]=true\n      -- Tag creator so kill leaderboards credit us\n      local tag=h:FindFirstChild(\"creator\")or Instance.new(\"ObjectValue\")\n      tag.Name=\"creator\";tag.Value=char;tag.Parent=h\n      h:TakeDamage(DAMAGE)\n      local r=char:FindFirstChild(\"HumanoidRootPart\")local root=p.Parent:FindFirstChild(\"HumanoidRootPart\")\n      if r and root then root.Velocity=(root.Position-r.Position).Unit*45+Vector3.new(0,25,0)end\n      task.delay(1,function()if tag and tag.Parent then tag:Destroy()end end)\n    end\n  end\n  task.wait(CD);active=true\nend)\nTool.Equipped:Connect(function()active=true;Handle.CanBeTouched=true end)\nTool.Unequipped:Connect(function()active=false end)\n\`\`\`\n\n**Setup:** In StarterPack insert a Tool named "Sword" (RequiresHandle=true), add a Part named "Handle" (Shape=Block, Size=(1,1,4)), and put this Script inside the Tool.`+KEYNOTE;}

function petTpl(n){return `## 🐾 Follow Pet\n\nPet follows behind your character with smooth lerp and bobbing animation.\n\n\`\`\`lua\n-- @location StarterCharacterScripts.Pet\nlocal RS=game:GetService(\"RunService\")\nlocal char=script.Parent;local hrp=char:WaitForChild(\"HumanoidRootPart\")\nlocal pet=char:FindFirstChild(\"Pet\")\nif not pet then\n  local b=Instance.new(\"Part\");b.Name=\"Pet\";b.Size=Vector3.new(2,2,2);b.Shape=Enum.PartType.Ball\n  b.Color=Color3.fromRGB(255,140,0);b.Material=Enum.Material.Neon;b.Anchored=true;b.CanCollide=false\n  b.Parent=char;pet=b\nend\nlocal cf0=CFrame.new(-3,2.5,0);local bob=0\nRS.RenderStepped:Connect(function(dt)\n  bob+=dt*4\n  local target=hrp.CFrame:ToWorldSpace(cf0)*CFrame.new(0,math.sin(bob)*0.3,0)\n  pet.CFrame=pet.CFrame:Lerp(target,math.min(1,dt*8))\nend)\n\`\`\`\n\n**Setup:** Put this LocalScript in StarterCharacterScripts. A default neon tiger-orange ball spawns. Swap the pet Part for your own Model (set PrimaryPart).`+KEYNOTE;}

function roundTpl(n){return `## ⚔️ Round-Based Arena\n\nServer loop: Intermission → Teleport to arena → Fight until one remains → Winner announcement → Return to lobby.\n\n\`\`\`lua\n-- @location ServerScriptService.RoundManager\nlocal Players=game:GetService(\"Players\");local RS=game:GetService(\"ReplicatedStorage\")\nlocal Status=Instance.new(\"StringValue\");Status.Name=\"Status\";Status.Parent=RS\nlocal INT=10;local ROUND=90;local MIN=2\nlocal lobby=workspace:FindFirstChild(\"Lobby\",true)local arena=workspace:FindFirstChild(\"Arena\",true)\nwhile true do\n  while#Players:GetPlayers()<MIN do Status.Value=\"Need \"..(MIN-#Players:GetPlayers())..\" more...\";task.wait(1)end\n  for i=INT,1,-1 do Status.Value=\"Intermission: \"..i;task.wait(1)end\n  local alive={}\n  for _,p in Players:GetPlayers()do\n    if p.Character and p.Character:FindFirstChild(\"HumanoidRootPart\")and arena then\n      p.Character:PivotTo(arena.CFrame+Vector3.new(math.random(-10,10),3,math.random(-10,10)))\n      table.insert(alive,p)\n    end\n  end\n  for i=ROUND,1,-1 do\n    alive={}\n    for _,p in Players:GetPlayers()do if p.Character and p.Character:FindFirstChildOfClass(\"Humanoid\")and p.Character.Humanoid.Health>0 then table.insert(alive,p)end end\n    if #alive<=1 then break end\n    Status.Value=\"FIGHT! \"..i..\"s — \"..#alive..\" left\";task.wait(1)\n  end\n  local w=alive[1];Status.Value=w and(w.DisplayName:\" wins!\")or\"Draw!\";task.wait(5)\n  for _,p in Players:GetPlayers()do if p.Character and lobby then p.Character:PivotTo(lobby.CFrame+Vector3.new(math.random(-5,5),3,math.random(-5,5)));p.Character:FindFirstChildOfClass(\"Humanoid\"):TakeDamage(0);p.Character:FindFirstChildOfClass(\"Humanoid\").Health=p.Character:FindFirstChildOfClass(\"Humanoid\").MaxHealth end end\nend\n\`\`\`\n\n**Setup:** Put SpawnLocations named Lobby and Arena in Workspace. Auto-creates Status StringValue in ReplicatedStorage.`+KEYNOTE;}

function adminTpl(n){return `## 👑 Admin Commands\n\nChat commands for you: /kill name, /respawn name, /bring name, /to name, /kick name, /speed 50, /ff name.\n\n\`\`\`lua\n-- @location ServerScriptService.Admin\nlocal Players=game:GetService(\"Players\")\nlocal ADMINS={[\"YourUsername\"]=true}-- EDIT ME\nlocal function findP(q)q=q:lower();for _,p in Players:GetPlayers()do if p.Name:lower():sub(1,#q)==q then return p end end end\nPlayers.PlayerAdded:Connect(function(p)p.Chatted:Connect(function(m)\n  if not ADMINS[p.Name]then return end\n  local cmd,arg=m:match(\"^/(%w+)%s*(.*)\");if not cmd then return end\n  local t=findP(arg)\n  if cmd==\"kill\"and t and t.Character then t.Character:FindFirstChildOfClass(\"Humanoid\").Health=0\n  elseif cmd==\"respawn\"and t then t:LoadCharacter()\n  elseif cmd==\"bring\"and t and t.Character and p.Character then t.Character:PivotTo(p.Character:GetPivot()*CFrame.new(0,0,5))\n  elseif cmd==\"to\"and t and t.Character and p.Character then p.Character:PivotTo(t.Character:GetPivot()*CFrame.new(0,0,5))\n  elseif cmd==\"kick\"and t then t:Kick(\"Kicked by admin\")\n  elseif cmd==\"speed\"then local n=tonumber(arg)or 50;if p.Character then p.Character:FindFirstChildOfClass(\"Humanoid\").WalkSpeed=n end\n  elseif cmd==\"ff\"then t=t or p;if t and t.Character then local f=Instance.new(\"ForceField\");f.Parent=t.Character;task.delay(30,function()if f then f:Destroy()end end)end\n  end\nend)end)\n\`\`\`\n\n**Setup:** Replace "YourUsername" with your Roblox name. Works only when you're in-game.`+KEYNOTE;}

function tycoonTpl(n){return `## 🏭 Tycoon Dropper\n\nDrops parts from above that fall onto a collector — touching gives the nearest player cash.\n\n\`\`\`lua\n-- @location ServerScriptService.Tycoon\nlocal Players=game:GetService(\"Players\")\nPlayers.PlayerAdded:Connect(function(p)local ls=Instance.new(\"Folder\");ls.Name=\"leaderstats\"local c=Instance.new(\"IntValue\");c.Name=\"Cash\";c.Value=100;c.Parent=ls;ls.Parent=p end)\nlocal dropper=workspace:WaitForChild(\"Dropper\")local spawn=dropper:WaitForChild(\"Spawn\")local collector=workspace:WaitForChild(\"Collector\")\nwhile task.wait(1)do\n  local p=Instance.new(\"Part\");p.Size=Vector3.new(1,1,1);p.Material=Enum.Material.Metal;p.Color=Color3.fromHSV(math.random(),0.7,0.9);p.CFrame=spawn.CFrame;p.Parent=workspace\n  local done=false;p.Touched:Connect(function(h)\n    if done then return end\n    if h:IsDescendantOf(collector)then done=true\n      local near,d=nil,50\n      for _,pl in Players:GetPlayers()do if pl.Character and pl.Character:FindFirstChild(\"HumanoidRootPart\")then local dd=(pl.Character.HumanoidRootPart.Position-p.Position).Magnitude;if dd<d then d=dd;near=pl end end end\n      if near then near.leaderstats.Cash.Value+=5 end\n      p:Destroy()\n    end\n  end)\n  task.delay(20,function()if p then p:Destroy()end end)\nend\n\`\`\`\n\n**Setup:** In Workspace, make a Part named "Dropper" high up with a child Part named "Spawn" (where parts spawn). Put a big Part named "Collector" on the ground below.`+KEYNOTE;}

function lbTpl(n){return `## 📊 Leaderstats (Coins/Kills/Wins)\n\nAuto-creates leaderboard stats and tracks kills when a "creator" tag is set (works with Sword tool above).\n\n\`\`\`lua\n-- @location ServerScriptService.Leaderstats\nlocal Players=game:GetService(\"Players\")\nPlayers.PlayerAdded:Connect(function(p)\n  local ls=Instance.new(\"Folder\");ls.Name=\"leaderstats\"\n  for _,n in ipairs({\"Coins\",\"Kills\",\"Wins\"})do local v=Instance.new(\"IntValue\");v.Name=n;v.Value=0;v.Parent=ls end\n  ls.Parent=p\n  p.CharacterAdded:Connect(function(c)c:WaitForChild(\"Humanoid\").Died:Connect(function()\n    local tag=c.Humanoid:FindFirstChild(\"creator\")\n    if tag and tag.Value then local k=Players:GetPlayerFromCharacter(tag.Value.Parent);if k and k:FindFirstChild(\"leaderstats\")then k.leaderstats.Kills.Value+=1 end end\n  end)end)\n  p:LoadCharacter()\nend)\n\`\`\`\n\nLeaderstats appear automatically in the Roblox player list (top-right corner).`+KEYNOTE;}

function shopTpl(n){return `## 🛒 Shop System\n\nProximityPrompt shop: walk up, press E, buy tools/upgrades with Cash.\n\n\`\`\`lua\n-- @location ServerScriptService.Shop\nlocal RS=game:GetService(\"ReplicatedStorage\");local Players=game:GetService(\"Players\")\nlocal buy=RS:FindFirstChild(\"BuyItem\")or Instance.new(\"RemoteEvent\");buy.Name=\"BuyItem\";buy.Parent=RS\nlocal ITEMS={Sword={price=50,tool=game.ServerStorage:FindFirstChild(\"Sword\")},Bow={price=75,tool=game.ServerStorage:FindFirstChild(\"Bow\")}}\nbuy.OnServerEvent:Connect(function(p,id)\n  local it=ITEMS[id];if not it then return end\n  local ls=p:FindFirstChild(\"leaderstats\");if not ls or not ls:FindFirstChild(\"Cash\")or ls.Cash.Value<it.price then return end\n  if p.Backpack:FindFirstChild(id)or(p.Character and p.Character:FindFirstChild(id))then return end\n  ls.Cash.Value-=it.price;if it.tool then it.tool:Clone().Parent=p.Backpack end\nend)\n\`\`\`\n\n**Setup:** Put Tools in ServerStorage (e.g. "Sword", "Bow"). For each item, put a Part in Workspace with a ProximityPrompt named "Buy_Sword" (ActionText="Buy Sword - 50g", HoldDuration=0.5).`+KEYNOTE;}

function obbyTpl(n){return `## 🪜 Obby Checkpoints\n\nTouch checkpoint to save; respawn there on death.\n\n\`\`\`lua\n-- @location ServerScriptService.ObbyCheckpoints\nlocal Players=game:GetService(\"Players\")\nlocal cps={};for i=1,20 do local p=workspace:FindFirstChild(\"Checkpoint\"..i);if p then table.insert(cps,p)end end\nPlayers.PlayerAdded:Connect(function(p)\n  local cp=1;p.CharacterAdded:Connect(function(c)task.wait(0.3)if cps[cp]then c:PivotTo(cps[cp].CFrame+Vector3.new(0,4,0))end end);p:LoadCharacter()\n  for i,part in ipairs(cps)do part.Touched:Connect(function(h)local pl=Players:GetPlayerFromCharacter(h.Parent);if pl==p and i>cp then cp=i end end)end\nend)\n\`\`\`\n\n**Setup:** Place Parts named Checkpoint1, Checkpoint2... along your obby.`+KEYNOTE;}

function dsTpl(n){return `## 💾 DataStore Save System\n\nAuto-saves Coins/Level/Xp on leave, with pcall safety and BindToClose.\n\n\`\`\`lua\n-- @location ServerScriptService.DataStore\nlocal DSS=game:GetService(\"DataStoreService\");local Players=game:GetService(\"Players\")\nlocal ds=DSS:GetDataStore(\"EnesAI_v1\")\nlocal DEF={Coins=0,Level=1,Xp=0}\nPlayers.PlayerAdded:Connect(function(p)\n  local ls=Instance.new(\"Folder\");ls.Name=\"leaderstats\";ls.Parent=p\n  local ok,d=pcall(function()return ds:GetAsync(\"p_\"..p.UserId)end);d=ok and d or DEF\n  for k,v in pairs(DEF)do local iv=Instance.new(\"IntValue\");iv.Name=k;iv.Value=d[k]or v;iv.Parent=ls end\nend)\nlocal function save(p)local ls=p:FindFirstChild(\"leaderstats\");if not ls then return end local d={};for _,c in ls:GetChildren()do d[c.Name]=c.Value end pcall(function()ds:SetAsync(\"p_\"..p.UserId,d)end)end\nPlayers.PlayerRemoving:Connect(save);game:BindToClose(function()for _,p in Players:GetPlayers()do save(p)end end)\nwhile task.wait(60)do for _,p in Players:GetPlayers()do save(p)end end\n\`\`\`\n\nEnable **Studio Access to API Services** in Game Settings → Security to test locally.`+KEYNOTE;}

function genericTpl(n,slug){return `## 🐯 Building: "${slug}"\n\nHere's a production-ready starter for "${slug}". Send it to Studio with 📤, then tell me what features to add.\n\n\`\`\`lua\n-- @location ServerScriptService.${n}\nlocal Players=game:GetService(\"Players\")local RS=game:GetService(\"ReplicatedStorage\")\nlocal remote=RS:FindFirstChild(\"${n}\")or Instance.new(\"RemoteEvent\")\nremote.Name=\"${n}\";remote.Parent=RS\nremote.OnServerEvent:Connect(function(pl,action,...)\n  if type(action)~=\"string\"then return end\n  print(\"[${n}]\",pl.Name,action,...)\nend)\n\`\`\`\n\n\`\`\`lua\n-- @location StarterPlayerScripts.${n}Client\nlocal RS=game:GetService(\"ReplicatedStorage\")local Players=game:GetService(\"Players\")\nlocal remote=RS:WaitForChild(\"${n}\")local lp=Players.LocalPlayer\nprint(\"${n} client ready\",lp.Name)\n\`\`\`\n\nTell me what this system should DO ("make it spawn enemies every 5s", "save data when player leaves", etc.) and I'll write the full logic.`+KEYNOTE;}

function fixTpl(slug){return `## 🔧 Debugging "${slug}"\n\nTo fix bugs I need to see your code or errors:\n\n1. Open **View → Output** in Studio — red error lines show exact file + line number\n2. Select the broken script, then click **↑ Script** in the Enes AI plugin panel (it sends me the full source)\n3. Click **📊 Scan Project** so I see your game structure\n4. Or paste the error/script right here in chat\n\nCommon Roblox fixes I can do in one shot:\n- Replace \`thing.Name\` with \`thing:WaitForChild(\"Name\")\` for late-loading objects\n- Wrap DataService/HttpService calls in pcall() (they fail sometimes)\n- Move Server scripts to ServerScriptService, LocalScripts to StarterPlayerScripts/StarterGui\n- Add RemoteEvents in ReplicatedStorage for client↔server (validate everything server-side!)\n- Add debounces to Touched events to prevent double-firing\n\nSend me the error and we'll fix it. 🐯`+KEYNOTE;}

function explainTpl(slug){return `## 📘 ${slug}\n\nAsk me anything specific — paste code or describe a concept and I'll break it down with examples. Quick starters:\n\n- **Server ↔ Client**: Server scripts (ServerScriptService) hold authority. LocalScripts (StarterPlayerScripts) handle UI/input. Communicate via RemoteEvent/RemoteFunction in ReplicatedStorage — **always validate on the server**, never trust the client.\n- **WaitForChild**: Use \`obj:WaitForChild(\"Part\")\` instead of \`obj.Part\` when something might not exist yet (safer, no errors).\n- **task.spawn / task.wait**: Modern Roblox scheduler — prefer over old wait()/delay()/spawn().\n- **CollectionService**: Tag objects (View → Tag Editor) and react with \`:GetTagged(\"MyTag\")\` and \`GetInstanceAddedSignal\`.\n- **Humanoid.TakeDamage(n)**: Respects ForceFields; sets creator tag if you set the "creator" ObjectValue.\n\nSend me a script or question and I'll go deeper. 🐯`+KEYNOTE;}

module.exports = { smartMockReply };
